package zhou.er.model;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class PoBudgetDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.id
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.status
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.budget_num
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private String budgetNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.shop_id
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.brand_id
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.channel_id
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Long channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.batch_month
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Integer batchMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.budget_fee
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private BigDecimal budgetFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.budget_start
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date budgetStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.budget_end
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date budgetEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.threshold
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private BigDecimal threshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.reserved_fee
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private BigDecimal reservedFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.reserved_start
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date reservedStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.reserved_end
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date reservedEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.creater_id
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Long createrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.delay
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Boolean delay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.actual_start
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date actualStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.actual_end
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date actualEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.gmt_create
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_budget.gmt_modify
     *
     * @mbg.generated Thu Sep 19 09:00:39 CST 2019
     */
    private Date gmtModify;

}